
'use client';

import React from 'react';
import { AIContext } from '@/types';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Bot, Terminal, Code2 } from 'lucide-react';

interface AIContextCardProps {
  context: AIContext;
}

const toolIcons = {
  Antigravity: <Bot className="h-4 w-4" />,
  Cursor: <Terminal className="h-4 w-4" />,
  Manual: <Code2 className="h-4 w-4" />,
};

export function AIContextCard({ context }: AIContextCardProps) {
  return (
    <Card className="bg-slate-50 border-blue-100">
      <CardHeader className="py-3 px-4 flex flex-row items-center justify-between space-y-0">
        <div className="flex items-center gap-2">
           <span className="p-1.5 bg-blue-100 rounded-md text-blue-600">
             {toolIcons[context.source_tool] || <Bot className="h-4 w-4" />}
           </span>
           <CardTitle className="text-sm font-medium">Generated by {context.source_tool}</CardTitle>
        </div>
        <div className="text-xs text-muted-foreground">
            {new Date(context.created_at).toLocaleDateString()}
        </div>
      </CardHeader>
      <CardContent className="px-4 py-2 pb-4">
        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="prompt" className="border-b-0">
            <AccordionTrigger className="py-2 text-xs font-normal text-muted-foreground hover:no-underline">
              View Original Prompt
            </AccordionTrigger>
            <AccordionContent>
              <div className="p-3 bg-white rounded-md border text-sm font-mono whitespace-pre-wrap max-h-[300px] overflow-y-auto">
                {context.original_prompt}
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </CardContent>
    </Card>
  );
}
