import { describe, it, expect } from 'vitest';
import {
  renderContext,
  renderClaude,
  renderCursor,
  renderCopilot,
  renderWindsurf,
  renderCursorMdc,
} from '../renderers.js';
import type { ContextIR } from '../context-ir.js';
import type { FocusArea } from '../task-focus.js';
import type { SmartRecommendation } from '../smart-context.js';

// ─── Fixtures ───

function makeIR(overrides: Partial<ContextIR> = {}): ContextIR {
  return {
    version: '1.0',
    generatedAt: '2026-03-01T00:00:00.000Z',
    project: {
      name: 'TestProject',
      techStack: ['Next.js', 'React', 'TypeScript'],
      packageManager: 'pnpm',
      nodeVersion: '20.11.0',
    },
    architecture: {
      layers: [
        { type: 'pages', items: ['/dashboard', '/login', '/settings'] },
        { type: 'api', items: ['GET /api/projects', 'POST /api/projects'] },
        { type: 'db', items: ['users', 'projects', 'tasks'] },
      ],
      importGraph: [
        { from: 'app/page.tsx', to: 'lib/utils.ts' },
        { from: 'app/page.tsx', to: 'components/Button.tsx' },
        { from: 'components/Button.tsx', to: 'lib/utils.ts' },
        { from: 'lib/db.ts', to: 'lib/schema.ts' },
      ],
      hubModules: [
        { path: 'lib/utils.ts', importedBy: 2 },
        { path: 'lib/schema.ts', importedBy: 1 },
      ],
    },
    activeWork: {
      tasks: [
        { id: 'task-001-abcdef1234567', title: 'Implement auth flow', status: 'in_progress', priority: 'high' },
        { id: 'task-002-bcdef2345678', title: 'Add dashboard charts', status: 'todo', priority: 'medium' },
        { id: 'task-003-cdef3456789a', title: 'Write unit tests', status: 'done', priority: 'low' },
      ],
      git: {
        branch: 'main',
        uncommittedChanges: 3,
        recentCommits: 12,
        totalCommits: 150,
      },
    },
    codeMap: {
      modules: [
        {
          path: 'lib/utils.ts',
          exports: [
            { name: 'cn', kind: 'function' },
            { name: 'formatDate', kind: 'function' },
          ],
          imports: [],
          importedBy: 2,
        },
        {
          path: 'components/Button.tsx',
          exports: [{ name: 'Button', kind: 'component' }],
          imports: ['lib/utils.ts'],
          importedBy: 1,
        },
        {
          path: 'types/index.ts',
          exports: [
            { name: 'Task', kind: 'type' },
            { name: 'Project', kind: 'type' },
          ],
          imports: [],
          importedBy: 0,
        },
      ],
      entryPoints: ['/dashboard', '/login', '/settings'],
      totalFiles: 80,
      totalLines: 9500,
      largestFiles: [
        { path: 'components/TaskList.tsx', lines: 580 },
        { path: 'lib/detector.ts', lines: 490 },
      ],
    },
    constraints: {
      envVars: ['DATABASE_URL', 'BETTER_AUTH_URL'],
      deployTarget: 'Vercel',
      ci: 'GitHub Actions',
      scripts: {
        dev: 'next dev',
        build: 'next build',
        test: 'vitest run',
      },
    },
    aiContext: {
      existingFiles: [{ name: 'CLAUDE.md', path: './CLAUDE.md' }],
    },
    ...overrides,
  };
}

function makeFocusAreas(): FocusArea[] {
  return [
    {
      taskId: 'task-001',
      taskTitle: 'Implement auth flow',
      primaryFiles: ['lib/auth.ts', 'app/login/page.tsx'],
      relatedModules: ['lib/db.ts'],
      relevantExports: [{ name: 'signIn', kind: 'function', file: 'lib/auth.ts' }],
      matchedKeywords: ['auth', 'login'],
    },
  ];
}

function makeSmartRecommendation(): SmartRecommendation {
  const scores = new Map<string, number>();
  scores.set('lib/auth.ts', 55);
  scores.set('lib/utils.ts', 30);
  return {
    activeFiles: ['lib/auth.ts', 'lib/utils.ts'],
    relatedModules: ['lib/db.ts'],
    suggestedExports: [{ name: 'signIn', kind: 'function', file: 'lib/auth.ts' }],
    workContext: 'Branch: feature/auth | Recent: add login | 5 files changed',
    relevanceScores: scores,
  };
}

// ─── Tests ───

describe('renderClaude', () => {
  it('includes auto-generated header with date', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('<!-- Generated by Orbit CLI on');
    expect(output).toContain('Do not edit above this line -->');
  });

  it('includes project name', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('# Project: TestProject');
  });

  it('includes tech stack', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Tech Stack');
    expect(output).toContain('Next.js / React / TypeScript');
  });

  it('includes package manager', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('Package Manager: pnpm');
  });

  it('includes platform and CI', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('Platform: Vercel');
    expect(output).toContain('CI: GitHub Actions');
  });

  it('includes project structure sections', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Project Structure');
    expect(output).toContain('**Pages (3):**');
    expect(output).toContain('**API Routes (2):**');
    expect(output).toContain('**DB Tables (3):**');
  });

  it('includes key files section', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Key Files');
    expect(output).toContain('TaskList.tsx (580 lines)');
    expect(output).toContain('80 source files');
  });

  it('includes exports section', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Exports');
    expect(output).toContain('**Components (1):**');
    expect(output).toContain('Button');
    expect(output).toContain('**Functions (2):**');
    expect(output).toContain('cn');
    expect(output).toContain('**Types (2):**');
    expect(output).toContain('Task');
  });

  it('includes import graph section', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Import Graph');
    expect(output).toContain('`lib/utils.ts` (2 imports)');
  });

  it('includes active tasks', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Active Tasks');
    expect(output).toContain('### In Progress');
    expect(output).toContain('[ORB-task-00] Implement auth flow');
    expect(output).toContain('### To Do');
    expect(output).toContain('Add dashboard charts');
  });

  it('includes completion status', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Completion Status');
    expect(output).toContain('1/3 tasks done');
  });

  it('includes environment variables', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Environment Variables');
    expect(output).toContain('DATABASE_URL, BETTER_AUTH_URL');
  });

  it('includes scripts', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('## Scripts');
    expect(output).toContain('`dev`: `next dev`');
    expect(output).toContain('`build`: `next build`');
  });

  it('ends with auto-generated footer', () => {
    const output = renderClaude(makeIR());
    expect(output).toContain('<!-- End of auto-generated context -->');
  });

  it('shows "No task data available" when tasks are empty', () => {
    const ir = makeIR({ activeWork: { tasks: [], git: null } });
    const output = renderClaude(ir);
    expect(output).toContain('No task data available');
  });
});

describe('renderCursor', () => {
  it('includes Cursor Rules header', () => {
    const output = renderCursor(makeIR());
    expect(output).toContain('# Cursor Rules — TestProject');
    expect(output).toContain('Generated by Orbit CLI');
  });

  it('includes tech stack', () => {
    const output = renderCursor(makeIR());
    expect(output).toContain('## Tech Stack');
    expect(output).toContain('Next.js / React / TypeScript');
  });

  it('includes project structure', () => {
    const output = renderCursor(makeIR());
    expect(output).toContain('## Project Structure');
    expect(output).toContain('**Pages (3):**');
  });

  it('includes key modules', () => {
    const output = renderCursor(makeIR());
    expect(output).toContain('## Key Modules');
    expect(output).toContain('`lib/utils.ts`');
  });

  it('includes active work', () => {
    const output = renderCursor(makeIR());
    expect(output).toContain('## Active Work');
    expect(output).toContain('Implement auth flow');
  });

  it('includes constraints', () => {
    const output = renderCursor(makeIR());
    expect(output).toContain('## Environment Variables');
    expect(output).toContain('DATABASE_URL');
  });
});

describe('renderCopilot', () => {
  it('includes Copilot Instructions header', () => {
    const output = renderCopilot(makeIR());
    expect(output).toContain('# Copilot Instructions — TestProject');
    expect(output).toContain('<!-- Generated by Orbit CLI');
  });

  it('includes project overview with bold tech', () => {
    const output = renderCopilot(makeIR());
    expect(output).toContain('## Project Overview');
    expect(output).toContain('**Next.js**');
  });

  it('includes package manager', () => {
    const output = renderCopilot(makeIR());
    expect(output).toContain('`pnpm`');
  });

  it('includes project structure', () => {
    const output = renderCopilot(makeIR());
    expect(output).toContain('## Project Structure');
  });

  it('includes active work', () => {
    const output = renderCopilot(makeIR());
    expect(output).toContain('## Active Work');
  });
});

describe('renderWindsurf', () => {
  it('includes Windsurf Rules header', () => {
    const output = renderWindsurf(makeIR());
    expect(output).toContain('# Windsurf Rules — TestProject');
    expect(output).toContain('Generated by Orbit CLI');
  });

  it('includes tech stack', () => {
    const output = renderWindsurf(makeIR());
    expect(output).toContain('## Tech Stack');
    expect(output).toContain('Next.js / React / TypeScript');
  });

  it('includes project structure', () => {
    const output = renderWindsurf(makeIR());
    expect(output).toContain('## Project Structure');
  });

  it('includes key modules', () => {
    const output = renderWindsurf(makeIR());
    expect(output).toContain('## Key Modules');
  });

  it('includes active work', () => {
    const output = renderWindsurf(makeIR());
    expect(output).toContain('## Active Work');
  });
});

describe('renderContext', () => {
  it('dispatches to renderClaude for "claude" target', () => {
    const output = renderContext(makeIR(), 'claude');
    expect(output).toContain('# Project: TestProject');
    expect(output).toContain('<!-- Generated by Orbit CLI');
  });

  it('dispatches to renderCursor for "cursor" target', () => {
    const output = renderContext(makeIR(), 'cursor');
    expect(output).toContain('# Cursor Rules — TestProject');
  });

  it('dispatches to renderCopilot for "copilot" target', () => {
    const output = renderContext(makeIR(), 'copilot');
    expect(output).toContain('# Copilot Instructions — TestProject');
  });

  it('dispatches to renderWindsurf for "windsurf" target', () => {
    const output = renderContext(makeIR(), 'windsurf');
    expect(output).toContain('# Windsurf Rules — TestProject');
  });

  it('uses renderCursor for "cursor-mdc" target (single-file fallback)', () => {
    const output = renderContext(makeIR(), 'cursor-mdc');
    expect(output).toContain('# Cursor Rules — TestProject');
  });
});

describe('renderCursorMdc', () => {
  it('returns a Map with project.mdc', () => {
    const files = renderCursorMdc(makeIR());
    expect(files.has('project.mdc')).toBe(true);
  });

  it('project.mdc contains MDC front-matter', () => {
    const files = renderCursorMdc(makeIR());
    const content = files.get('project.mdc')!;
    expect(content).toContain('---');
    expect(content).toContain('description: Project overview');
    expect(content).toContain('alwaysApply: true');
  });

  it('project.mdc contains project name', () => {
    const files = renderCursorMdc(makeIR());
    expect(files.get('project.mdc')).toContain('# Project: TestProject');
  });

  it('project.mdc contains tech stack', () => {
    const files = renderCursorMdc(makeIR());
    expect(files.get('project.mdc')).toContain('Next.js / React / TypeScript');
  });

  it('returns tasks.mdc when tasks are present', () => {
    const files = renderCursorMdc(makeIR());
    expect(files.has('tasks.mdc')).toBe(true);
    expect(files.get('tasks.mdc')).toContain('Implement auth flow');
  });

  it('does not return tasks.mdc when tasks are empty', () => {
    const ir = makeIR({ activeWork: { tasks: [], git: null } });
    const files = renderCursorMdc(ir);
    expect(files.has('tasks.mdc')).toBe(false);
  });

  it('returns focus.mdc when focus areas are present', () => {
    const ir = makeIR({ focusAreas: makeFocusAreas() });
    const files = renderCursorMdc(ir);
    expect(files.has('focus.mdc')).toBe(true);
    expect(files.get('focus.mdc')).toContain('Task-linked');
  });

  it('does not return focus.mdc when no focus areas', () => {
    const files = renderCursorMdc(makeIR());
    expect(files.has('focus.mdc')).toBe(false);
  });

  it('returns smart.mdc when smart recommendation is present', () => {
    const ir = makeIR({ smartRecommendation: makeSmartRecommendation() });
    const files = renderCursorMdc(ir);
    expect(files.has('smart.mdc')).toBe(true);
    expect(files.get('smart.mdc')).toContain('AI-powered');
  });

  it('does not return smart.mdc when no recommendation', () => {
    const files = renderCursorMdc(makeIR());
    expect(files.has('smart.mdc')).toBe(false);
  });
});

describe('Focus section rendering', () => {
  it('renderClaude includes focus areas', () => {
    const ir = makeIR({ focusAreas: makeFocusAreas() });
    const output = renderClaude(ir);
    expect(output).toContain('## Focus Areas');
    expect(output).toContain('Task-linked context');
    expect(output).toContain('### Implement auth flow');
    expect(output).toContain('**Primary files:**');
    expect(output).toContain('`lib/auth.ts`');
    expect(output).toContain('**Related modules:**');
    expect(output).toContain('`lib/db.ts`');
    expect(output).toContain('**Key exports:**');
    expect(output).toContain('function: signIn');
  });

  it('renderCursor includes focus areas', () => {
    const ir = makeIR({ focusAreas: makeFocusAreas() });
    const output = renderCursor(ir);
    expect(output).toContain('## Focus Areas');
    expect(output).toContain('### Implement auth flow');
  });

  it('renderCopilot includes focus areas', () => {
    const ir = makeIR({ focusAreas: makeFocusAreas() });
    const output = renderCopilot(ir);
    expect(output).toContain('## Focus Areas');
  });

  it('renderWindsurf includes focus areas', () => {
    const ir = makeIR({ focusAreas: makeFocusAreas() });
    const output = renderWindsurf(ir);
    expect(output).toContain('## Focus Areas');
  });

  it('does not render focus section when no focus areas', () => {
    const output = renderClaude(makeIR());
    expect(output).not.toContain('## Focus Areas');
  });
});

describe('Smart Context section rendering', () => {
  it('renderClaude includes smart recommendation', () => {
    const ir = makeIR({ smartRecommendation: makeSmartRecommendation() });
    const output = renderClaude(ir);
    expect(output).toContain('## Recommended Focus (Smart Context)');
    expect(output).toContain('Branch: feature/auth');
    expect(output).toContain('**Active files**');
    expect(output).toContain('`lib/auth.ts` (score: 55)');
    expect(output).toContain('`lib/utils.ts` (score: 30)');
    expect(output).toContain('**Related modules:**');
    expect(output).toContain('`lib/db.ts`');
    expect(output).toContain('**Key exports in scope:**');
    expect(output).toContain('function: `signIn` in `lib/auth.ts`');
  });

  it('renderCursor includes smart recommendation', () => {
    const ir = makeIR({ smartRecommendation: makeSmartRecommendation() });
    const output = renderCursor(ir);
    expect(output).toContain('## Recommended Focus (Smart Context)');
  });

  it('renderCopilot includes smart recommendation', () => {
    const ir = makeIR({ smartRecommendation: makeSmartRecommendation() });
    const output = renderCopilot(ir);
    expect(output).toContain('## Recommended Focus (Smart Context)');
  });

  it('renderWindsurf includes smart recommendation', () => {
    const ir = makeIR({ smartRecommendation: makeSmartRecommendation() });
    const output = renderWindsurf(ir);
    expect(output).toContain('## Recommended Focus (Smart Context)');
  });

  it('does not render smart section when no recommendation', () => {
    const output = renderClaude(makeIR());
    expect(output).not.toContain('## Recommended Focus');
  });
});

describe('edge cases', () => {
  it('handles empty tech stack', () => {
    const ir = makeIR({
      project: { name: 'Bare', techStack: [], packageManager: null, nodeVersion: null },
      constraints: { envVars: [], deployTarget: null, ci: null, scripts: {} },
    });
    const output = renderClaude(ir);
    expect(output).toContain('# Project: Bare');
    expect(output).not.toContain('## Tech Stack');
  });

  it('handles no tasks and no git', () => {
    const ir = makeIR({
      activeWork: { tasks: [], git: null },
    });
    const output = renderClaude(ir);
    expect(output).toContain('No task data available');
    expect(output).not.toContain('## Git');
  });

  it('handles no architecture layers', () => {
    const ir = makeIR({
      architecture: { layers: [], importGraph: [], hubModules: [] },
    });
    const output = renderClaude(ir);
    expect(output).not.toContain('## Project Structure');
    expect(output).not.toContain('## Import Graph');
  });

  it('handles no exports', () => {
    const ir = makeIR({
      codeMap: {
        modules: [],
        entryPoints: [],
        totalFiles: 0,
        totalLines: 0,
        largestFiles: [],
      },
    });
    const output = renderClaude(ir);
    expect(output).not.toContain('## Exports');
    expect(output).not.toContain('## Key Files');
  });

  it('handles no env vars', () => {
    const ir = makeIR({
      constraints: { envVars: [], deployTarget: null, ci: null, scripts: {} },
    });
    const output = renderClaude(ir);
    expect(output).not.toContain('## Environment Variables');
    expect(output).not.toContain('## Scripts');
  });

  it('handles external issues', () => {
    const ir = makeIR({
      activeWork: {
        tasks: [],
        git: null,
        externalIssues: [
          { number: 42, title: 'Fix login bug', labels: ['bug', 'priority'], body: 'Login fails', state: 'open' as const, url: 'https://github.com/test/42', provider: 'github' },
          { number: 43, title: 'Add dark mode', labels: [], body: '', state: 'open' as const, url: 'https://github.com/test/43', provider: 'github' },
        ],
      },
    });
    const output = renderClaude(ir);
    expect(output).toContain('## GitHub Issues');
    expect(output).toContain('#42: Fix login bug [bug, priority]');
    expect(output).toContain('#43: Add dark mode');
  });

  it('large task list truncates to-do items', () => {
    const tasks = Array.from({ length: 15 }, (_, i) => ({
      id: `task-${i.toString().padStart(3, '0')}`,
      title: `Task ${i}`,
      status: 'todo' as const,
      priority: 'medium',
    }));
    const ir = makeIR({
      activeWork: { tasks, git: null },
    });
    const output = renderClaude(ir);
    expect(output).toContain('### To Do (Top 10)');
    expect(output).toContain('... and 5 more');
  });

  it('cursor-mdc handles many pages correctly', () => {
    const ir = makeIR({
      architecture: {
        ...makeIR().architecture,
        layers: [
          { type: 'pages', items: Array.from({ length: 20 }, (_, i) => `/page-${i}`) },
        ],
      },
    });
    const files = renderCursorMdc(ir);
    const content = files.get('project.mdc')!;
    expect(content).toContain('**Pages (20):**');
  });
});
