import type { ScanResult } from './detector.js';
import type { Task } from '../types.js';

export function generateContext(
  scan: ScanResult,
  tasks: Task[],
  projectName: string,
): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by Orbit CLI on ${now} — Do not edit above this line -->`);
  lines.push('');
  lines.push(`# Project: ${projectName}`);
  lines.push('');

  // ── Tech Stack ──
  if (scan.techStack.length > 0 || scan.packageManager || scan.deployment.platform || scan.deployment.ci) {
    lines.push('## Tech Stack');
    if (scan.techStack.length > 0) {
      lines.push(scan.techStack.join(' / '));
    }
    const meta: string[] = [];
    if (scan.packageManager) meta.push(`Package Manager: ${scan.packageManager}`);
    if (scan.deployment.platform) meta.push(`Platform: ${scan.deployment.platform}`);
    if (scan.deployment.ci) meta.push(`CI: ${scan.deployment.ci}`);
    if (meta.length > 0) {
      lines.push(`- ${meta.join('\n- ')}`);
    }
    lines.push('');
  }

  // ── Project Structure ──
  const { pages, apiRoutes, dbTables } = scan.structure;
  if (pages.length > 0 || apiRoutes.length > 0 || dbTables.length > 0) {
    lines.push('## Project Structure');
    if (pages.length > 0) {
      const pageList = pages.length > 12
        ? pages.slice(0, 12).join(' ') + ` +${pages.length - 12}`
        : pages.join(' ');
      lines.push(`- **Pages (${pages.length}):** ${pageList}`);
    }
    if (apiRoutes.length > 0) {
      const methods = [...new Set(apiRoutes.map(r => r.method))].join(', ');
      lines.push(`- **API Routes (${apiRoutes.length}):** ${methods}`);
    }
    if (dbTables.length > 0) {
      const tableNames = dbTables.map(t => t.name).join(', ');
      lines.push(`- **DB Tables (${dbTables.length}):** ${tableNames}`);
    }
    lines.push('');
  }

  // ── Key Files ──
  if (scan.codeMetrics.totalFiles > 0) {
    lines.push('## Key Files');
    if (scan.codeMetrics.largestFiles.length > 0) {
      const top = scan.codeMetrics.largestFiles.slice(0, 5)
        .map(f => `${f.path.split('/').pop()} (${f.lines} lines)`)
        .join(', ');
      lines.push(`- Largest: ${top}`);
    }
    lines.push(`- ${scan.codeMetrics.totalFiles} source files, ~${scan.codeMetrics.totalLines.toLocaleString()} lines`);
    lines.push('');
  }

  // ── Exports ──
  if (scan.exports.length > 0) {
    lines.push('## Exports');
    const components = scan.exports.filter(e => e.kind === 'component');
    const functions = scan.exports.filter(e => e.kind === 'function');
    const types = scan.exports.filter(e => e.kind === 'type');
    if (components.length > 0) {
      const display = components.slice(0, 20);
      lines.push(`- **Components (${components.length}):** ${display.map(e => e.name).join(', ')}${components.length > 20 ? ` +${components.length - 20}` : ''}`);
    }
    if (functions.length > 0) {
      const display = functions.slice(0, 20);
      lines.push(`- **Functions (${functions.length}):** ${display.map(e => e.name).join(', ')}${functions.length > 20 ? ` +${functions.length - 20}` : ''}`);
    }
    if (types.length > 0) {
      const display = types.slice(0, 20);
      lines.push(`- **Types (${types.length}):** ${display.map(e => e.name).join(', ')}${types.length > 20 ? ` +${types.length - 20}` : ''}`);
    }
    lines.push('');
  }

  // ── Import Graph Summary ──
  if (scan.importGraph.length > 0) {
    const totalImports = scan.importGraph.reduce((sum, f) => sum + f.imports.length, 0);
    // Find most-imported files (hub files)
    const importCount = new Map<string, number>();
    for (const { imports } of scan.importGraph) {
      for (const imp of imports) {
        importCount.set(imp, (importCount.get(imp) || 0) + 1);
      }
    }
    const hubs = [...importCount.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10);

    lines.push('## Import Graph');
    lines.push(`${scan.importGraph.length} files, ${totalImports} local imports`);
    if (hubs.length > 0) {
      lines.push('');
      lines.push('Most imported modules:');
      for (const [mod, count] of hubs) {
        lines.push(`- \`${mod}\` (${count} imports)`);
      }
    }
    lines.push('');
  }

  // ── Active Tasks ──
  const inProgress = tasks.filter(t => t.status === 'in_progress');
  const todo = tasks.filter(t => t.status === 'todo');
  const done = tasks.filter(t => t.status === 'done');
  const total = tasks.length;

  if (total > 0) {
    lines.push('## Active Tasks');

    if (inProgress.length > 0) {
      lines.push('### In Progress');
      for (const t of inProgress) {
        const shortId = t.id.slice(0, 7);
        lines.push(`- [ORB-${shortId}] ${t.title}`);
      }
      lines.push('');
    }

    if (todo.length > 0) {
      const display = todo.slice(0, 10);
      const remaining = todo.length - display.length;
      lines.push(`### To Do${todo.length > 10 ? ' (Top 10)' : ''}`);
      for (const t of display) {
        const shortId = t.id.slice(0, 7);
        lines.push(`- [ORB-${shortId}] ${t.title}`);
      }
      if (remaining > 0) {
        lines.push(`- ... and ${remaining} more`);
      }
      lines.push('');
    }

    // ── Completion Status ──
    const pct = total > 0 ? Math.round((done.length / total) * 100) : 0;
    lines.push('## Completion Status');
    lines.push(`${done.length}/${total} tasks done (${pct}%)`);
    lines.push('');
  } else {
    lines.push('## Tasks');
    lines.push('No task data available. Run `orbit login` + `orbit init` to include task context.');
    lines.push('');
  }

  // ── Environment Variables ──
  if (scan.envVars.length > 0) {
    lines.push('## Environment Variables');
    lines.push(scan.envVars.join(', '));
    lines.push('');
  }

  // ── Scripts ──
  const scriptNames = Object.keys(scan.scripts);
  if (scriptNames.length > 0) {
    lines.push('## Scripts');
    for (const name of scriptNames) {
      lines.push(`- \`${name}\`: \`${scan.scripts[name]}\``);
    }
    lines.push('');
  }

  lines.push('<!-- End of auto-generated context -->');
  lines.push('');

  return lines.join('\n');
}
