import type { ContextIR } from './context-ir.js';
import type { FocusArea } from './task-focus.js';
import type { Task } from '../types.js';

export function generatePlan(
  task: Task,
  ir: ContextIR,
  focusAreas: FocusArea[],
): string {
  const sections: string[] = [];

  // 1. Task overview
  sections.push(`# Implementation Plan: ${task.title}`);
  sections.push(`> Task ID: ${task.id.slice(0, 8)}`);
  sections.push(`> Priority: ${task.priority} | Status: ${task.status}`);
  if (task.description) {
    sections.push('');
    sections.push(`## Description`);
    sections.push(task.description);
  }
  sections.push('');

  // 2. Project context
  sections.push(`## Project Context`);
  sections.push(`- **Tech:** ${ir.project.techStack.join(', ')}`);
  sections.push(`- **Files:** ${ir.codeMap.totalFiles} (${ir.codeMap.totalLines.toLocaleString()} lines)`);
  if (ir.project.packageManager) {
    sections.push(`- **Package Manager:** ${ir.project.packageManager}`);
  }
  if (ir.constraints.deployTarget) {
    sections.push(`- **Deploy:** ${ir.constraints.deployTarget}`);
  }
  sections.push('');

  // 3. Affected files (from focus areas)
  if (focusAreas.length > 0) {
    sections.push(`## Affected Files`);
    for (const area of focusAreas) {
      if (area.primaryFiles.length > 0) {
        for (const f of area.primaryFiles) {
          sections.push(`- \`${f}\``);
        }
      }
      if (area.relatedModules.length > 0) {
        sections.push('');
        sections.push('**Related modules:**');
        for (const m of area.relatedModules) {
          sections.push(`- \`${m}\``);
        }
      }
    }
    sections.push('');
  }

  // 4. Dependencies
  if (focusAreas.length > 0) {
    const allPrimaryFiles = new Set(focusAreas.flatMap(a => a.primaryFiles));
    const relevantEdges = ir.architecture.importGraph.filter(
      e => allPrimaryFiles.has(e.from) || allPrimaryFiles.has(e.to)
    );
    if (relevantEdges.length > 0) {
      sections.push(`## Dependencies`);
      const importMap = new Map<string, string[]>();
      for (const edge of relevantEdges) {
        if (!importMap.has(edge.from)) importMap.set(edge.from, []);
        importMap.get(edge.from)!.push(edge.to);
      }
      for (const [from, tos] of importMap) {
        sections.push(`- \`${from}\` imports: ${tos.map(t => `\`${t}\``).join(', ')}`);
      }
      sections.push('');
    }
  }

  // 5. Suggested steps
  sections.push(`## Suggested Steps`);
  sections.push(`1. Review the affected files listed above`);
  sections.push(`2. Understand the current implementation patterns`);

  if (focusAreas.length > 0 && focusAreas[0].primaryFiles.length > 0) {
    const mainFile = focusAreas[0].primaryFiles[0];
    sections.push(`3. Start with \`${mainFile}\` as the primary entry point`);
  } else {
    sections.push(`3. Identify the primary entry point for this change`);
  }

  if (task.priority === 'high') {
    sections.push(`4. Implement the core change (high priority — handle first)`);
  } else {
    sections.push(`4. Implement the core change`);
  }

  sections.push(`5. Update any related tests`);
  sections.push(`6. Verify no regressions in dependent modules`);
  sections.push('');

  // 6. Relevant exports
  if (focusAreas.length > 0) {
    const allExports = focusAreas.flatMap(a => a.relevantExports);
    if (allExports.length > 0) {
      sections.push(`## Relevant Exports`);
      for (const exp of allExports.slice(0, 15)) {
        sections.push(`- \`${exp.name}\` (${exp.kind}) in \`${exp.file}\``);
      }
      sections.push('');
    }
  }

  // 7. Git context
  if (ir.activeWork.git) {
    sections.push(`## Current Git State`);
    sections.push(`- Branch: ${ir.activeWork.git.branch}`);
    sections.push(`- Uncommitted changes: ${ir.activeWork.git.uncommittedChanges}`);
    sections.push(`- Recent commits: ${ir.activeWork.git.recentCommits} this week`);
    sections.push('');
  }

  sections.push('---');
  sections.push('*Generated by `orbit plan` — Orbit CLI*');
  sections.push('');

  return sections.join('\n');
}
