import type { ContextIR } from './context-ir.js';
import type { FocusArea } from './task-focus.js';

export type RenderTarget = 'claude' | 'cursor' | 'cursor-mdc' | 'copilot' | 'windsurf';

export const RENDER_TARGETS: Record<RenderTarget, string> = {
  claude: 'CLAUDE.md',
  cursor: '.cursorrules',
  'cursor-mdc': '.cursor/rules/',
  copilot: '.github/copilot-instructions.md',
  windsurf: '.windsurfrules',
};

export function renderContext(ir: ContextIR, target: RenderTarget): string {
  switch (target) {
    case 'claude':
      return renderClaude(ir);
    case 'cursor':
      return renderCursor(ir);
    case 'cursor-mdc':
      // For MDC, renderContext returns the project overview as default.
      // Use renderCursorMdc() for multi-file output.
      return renderCursor(ir);
    case 'copilot':
      return renderCopilot(ir);
    case 'windsurf':
      return renderWindsurf(ir);
  }
}

/**
 * Render Cursor MDC format: returns a Map of filename → content
 * for writing to .cursor/rules/ directory.
 */
export function renderCursorMdc(ir: ContextIR): Map<string, string> {
  const files = new Map<string, string>();

  // project.mdc — Project overview + tech stack
  const projectLines: string[] = [];
  projectLines.push(`# Project: ${ir.project.name}`);
  projectLines.push('');
  if (ir.project.techStack.length > 0) {
    projectLines.push('## Tech Stack');
    projectLines.push(ir.project.techStack.join(' / '));
    const meta: string[] = [];
    if (ir.project.packageManager) meta.push(`Package manager: ${ir.project.packageManager}`);
    if (ir.constraints.deployTarget) meta.push(`Platform: ${ir.constraints.deployTarget}`);
    if (ir.constraints.ci) meta.push(`CI: ${ir.constraints.ci}`);
    if (meta.length > 0) projectLines.push(meta.join(' | '));
    projectLines.push('');
  }
  renderStructureSection(ir, projectLines);
  renderKeyModulesSection(ir, projectLines);
  renderConstraintsSection(ir, projectLines);
  files.set('project.mdc', renderMdcFile('Project overview, tech stack, and structure', projectLines.join('\n')));

  // tasks.mdc — Active tasks
  if (ir.activeWork.tasks.length > 0) {
    const taskLines: string[] = [];
    renderActiveWorkSection(ir, taskLines);
    files.set('tasks.mdc', renderMdcFile('Active tasks and current work', taskLines.join('\n')));
  }

  // focus.mdc — Focus areas (if present)
  if (ir.focusAreas && ir.focusAreas.length > 0) {
    const focusLines: string[] = [];
    renderFocusSection(ir, focusLines);
    files.set('focus.mdc', renderMdcFile('Task-linked focus areas', focusLines.join('\n')));
  }

  // smart.mdc — Smart context recommendations (if present)
  if (ir.smartRecommendation) {
    const smartLines: string[] = [];
    renderSmartSection(ir, smartLines);
    files.set('smart.mdc', renderMdcFile('AI-powered context recommendations', smartLines.join('\n')));
  }

  return files;
}

function renderMdcFile(description: string, content: string): string {
  return `---\ndescription: ${description}\nglobs: \nalwaysApply: true\n---\n\n${content}`;
}

// ─── CLAUDE.md ───
// Must produce byte-identical output to the old generateContext()

export function renderClaude(ir: ContextIR): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 10);

  lines.push(`<!-- Generated by Orbit CLI on ${now} — Do not edit above this line -->`);
  lines.push('');
  lines.push(`# Project: ${ir.project.name}`);
  lines.push('');

  // ── Tech Stack ──
  const hasStack = ir.project.techStack.length > 0 || ir.project.packageManager ||
    ir.constraints.deployTarget || ir.constraints.ci;
  if (hasStack) {
    lines.push('## Tech Stack');
    if (ir.project.techStack.length > 0) {
      lines.push(ir.project.techStack.join(' / '));
    }
    const meta: string[] = [];
    if (ir.project.packageManager) meta.push(`Package Manager: ${ir.project.packageManager}`);
    if (ir.constraints.deployTarget) meta.push(`Platform: ${ir.constraints.deployTarget}`);
    if (ir.constraints.ci) meta.push(`CI: ${ir.constraints.ci}`);
    if (meta.length > 0) {
      lines.push(`- ${meta.join('\n- ')}`);
    }
    lines.push('');
  }

  // ── Project Structure ──
  const pagesLayer = ir.architecture.layers.find(l => l.type === 'pages');
  const apiLayer = ir.architecture.layers.find(l => l.type === 'api');
  const dbLayer = ir.architecture.layers.find(l => l.type === 'db');
  const pages = pagesLayer?.items ?? [];
  const apiRoutes = apiLayer?.items ?? [];
  const dbTables = dbLayer?.items ?? [];

  if (pages.length > 0 || apiRoutes.length > 0 || dbTables.length > 0) {
    lines.push('## Project Structure');
    if (pages.length > 0) {
      const pageList = pages.length > 12
        ? pages.slice(0, 12).join(' ') + ` +${pages.length - 12}`
        : pages.join(' ');
      lines.push(`- **Pages (${pages.length}):** ${pageList}`);
    }
    if (apiRoutes.length > 0) {
      // Extract unique methods from "METHOD /path" format
      const methods = [...new Set(apiRoutes.map(r => r.split(' ')[0]))].join(', ');
      lines.push(`- **API Routes (${apiRoutes.length}):** ${methods}`);
    }
    if (dbTables.length > 0) {
      const tableNames = dbTables.join(', ');
      lines.push(`- **DB Tables (${dbTables.length}):** ${tableNames}`);
    }
    lines.push('');
  }

  // ── Key Files ──
  if (ir.codeMap.totalFiles > 0) {
    lines.push('## Key Files');
    if (ir.codeMap.largestFiles.length > 0) {
      const top = ir.codeMap.largestFiles.slice(0, 5)
        .map(f => `${f.path.split('/').pop()} (${f.lines} lines)`)
        .join(', ');
      lines.push(`- Largest: ${top}`);
    }
    lines.push(`- ${ir.codeMap.totalFiles} source files, ~${ir.codeMap.totalLines.toLocaleString()} lines`);
    lines.push('');
  }

  // ── Exports ──
  const allExports = ir.codeMap.modules.flatMap(m => m.exports);
  if (allExports.length > 0) {
    lines.push('## Exports');
    const components = allExports.filter(e => e.kind === 'component');
    const functions = allExports.filter(e => e.kind === 'function');
    const types = allExports.filter(e => e.kind === 'type');
    if (components.length > 0) {
      const display = components.slice(0, 20);
      lines.push(`- **Components (${components.length}):** ${display.map(e => e.name).join(', ')}${components.length > 20 ? ` +${components.length - 20}` : ''}`);
    }
    if (functions.length > 0) {
      const display = functions.slice(0, 20);
      lines.push(`- **Functions (${functions.length}):** ${display.map(e => e.name).join(', ')}${functions.length > 20 ? ` +${functions.length - 20}` : ''}`);
    }
    if (types.length > 0) {
      const display = types.slice(0, 20);
      lines.push(`- **Types (${types.length}):** ${display.map(e => e.name).join(', ')}${types.length > 20 ? ` +${types.length - 20}` : ''}`);
    }
    lines.push('');
  }

  // ── Import Graph Summary ──
  if (ir.architecture.importGraph.length > 0) {
    const fileCount = new Set(ir.architecture.importGraph.map(e => e.from)).size;
    const totalImports = ir.architecture.importGraph.length;
    const hubs = ir.architecture.hubModules;

    lines.push('## Import Graph');
    lines.push(`${fileCount} files, ${totalImports} local imports`);
    if (hubs.length > 0) {
      lines.push('');
      lines.push('Most imported modules:');
      for (const hub of hubs) {
        lines.push(`- \`${hub.path}\` (${hub.importedBy} imports)`);
      }
    }
    lines.push('');
  }

  // ── Focus Areas ──
  renderFocusSection(ir, lines);

  // ── Smart Context ──
  renderSmartSection(ir, lines);

  // ── Active Tasks ──
  const inProgress = ir.activeWork.tasks.filter(t => t.status === 'in_progress');
  const todo = ir.activeWork.tasks.filter(t => t.status === 'todo');
  const done = ir.activeWork.tasks.filter(t => t.status === 'done');
  const total = ir.activeWork.tasks.length;

  if (total > 0) {
    lines.push('## Active Tasks');

    if (inProgress.length > 0) {
      lines.push('### In Progress');
      for (const t of inProgress) {
        const shortId = t.id.slice(0, 7);
        lines.push(`- [ORB-${shortId}] ${t.title}`);
      }
      lines.push('');
    }

    if (todo.length > 0) {
      const display = todo.slice(0, 10);
      const remaining = todo.length - display.length;
      lines.push(`### To Do${todo.length > 10 ? ' (Top 10)' : ''}`);
      for (const t of display) {
        const shortId = t.id.slice(0, 7);
        lines.push(`- [ORB-${shortId}] ${t.title}`);
      }
      if (remaining > 0) {
        lines.push(`- ... and ${remaining} more`);
      }
      lines.push('');
    }

    // ── Completion Status ──
    const pct = total > 0 ? Math.round((done.length / total) * 100) : 0;
    lines.push('## Completion Status');
    lines.push(`${done.length}/${total} tasks done (${pct}%)`);
    lines.push('');
  } else {
    lines.push('## Tasks');
    lines.push('No task data available. Run `orbit login` + `orbit init` to include task context.');
    lines.push('');
  }

  // ── External Issues ──
  renderExternalIssuesSection(ir, lines);

  // ── Environment Variables ──
  if (ir.constraints.envVars.length > 0) {
    lines.push('## Environment Variables');
    lines.push(ir.constraints.envVars.join(', '));
    lines.push('');
  }

  // ── Scripts ──
  const scriptNames = Object.keys(ir.constraints.scripts);
  if (scriptNames.length > 0) {
    lines.push('## Scripts');
    for (const name of scriptNames) {
      lines.push(`- \`${name}\`: \`${ir.constraints.scripts[name]}\``);
    }
    lines.push('');
  }

  lines.push('<!-- End of auto-generated context -->');
  lines.push('');

  return lines.join('\n');
}

// ─── .cursorrules ───

export function renderCursor(ir: ContextIR): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 10);

  lines.push(`# Cursor Rules — ${ir.project.name}`);
  lines.push(`# Generated by Orbit CLI on ${now}`);
  lines.push('');

  // Tech stack
  if (ir.project.techStack.length > 0) {
    lines.push('## Tech Stack');
    lines.push(ir.project.techStack.join(' / '));
    if (ir.project.packageManager) {
      lines.push(`Package manager: ${ir.project.packageManager}`);
    }
    lines.push('');
  }

  // Project structure
  renderStructureSection(ir, lines);

  // Key modules
  renderKeyModulesSection(ir, lines);

  // Focus areas
  renderFocusSection(ir, lines);

  // Smart context
  renderSmartSection(ir, lines);

  // Active work
  renderActiveWorkSection(ir, lines);

  // Constraints
  renderConstraintsSection(ir, lines);

  return lines.join('\n');
}

// ─── .github/copilot-instructions.md ───

export function renderCopilot(ir: ContextIR): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 10);

  lines.push(`# Copilot Instructions — ${ir.project.name}`);
  lines.push(`<!-- Generated by Orbit CLI on ${now} -->`);
  lines.push('');
  lines.push('## Project Overview');
  lines.push('');

  if (ir.project.techStack.length > 0) {
    lines.push(`This project uses **${ir.project.techStack.join('**, **')}**.`);
  }
  if (ir.project.packageManager) {
    lines.push(`Package manager: \`${ir.project.packageManager}\``);
  }
  lines.push('');

  // Project structure
  renderStructureSection(ir, lines);

  // Key modules
  renderKeyModulesSection(ir, lines);

  // Focus areas
  renderFocusSection(ir, lines);

  // Smart context
  renderSmartSection(ir, lines);

  // Active work
  renderActiveWorkSection(ir, lines);

  // Constraints
  renderConstraintsSection(ir, lines);

  return lines.join('\n');
}

// ─── .windsurfrules ───

export function renderWindsurf(ir: ContextIR): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 10);

  lines.push(`# Windsurf Rules — ${ir.project.name}`);
  lines.push(`# Generated by Orbit CLI on ${now}`);
  lines.push('');

  // Tech stack
  if (ir.project.techStack.length > 0) {
    lines.push('## Tech Stack');
    lines.push(ir.project.techStack.join(' / '));
    if (ir.project.packageManager) {
      lines.push(`Package manager: ${ir.project.packageManager}`);
    }
    lines.push('');
  }

  // Project structure
  renderStructureSection(ir, lines);

  // Key modules
  renderKeyModulesSection(ir, lines);

  // Focus areas
  renderFocusSection(ir, lines);

  // Smart context
  renderSmartSection(ir, lines);

  // Active work
  renderActiveWorkSection(ir, lines);

  // Constraints
  renderConstraintsSection(ir, lines);

  return lines.join('\n');
}

// ─── Shared helpers for non-Claude renderers ───

function renderStructureSection(ir: ContextIR, lines: string[]): void {
  const pagesLayer = ir.architecture.layers.find(l => l.type === 'pages');
  const apiLayer = ir.architecture.layers.find(l => l.type === 'api');
  const dbLayer = ir.architecture.layers.find(l => l.type === 'db');

  if (pagesLayer || apiLayer || dbLayer) {
    lines.push('## Project Structure');
    if (pagesLayer) {
      lines.push(`- **Pages (${pagesLayer.items.length}):** ${pagesLayer.items.join(' ')}`);
    }
    if (apiLayer) {
      lines.push(`- **API Routes (${apiLayer.items.length}):** ${apiLayer.items.join(', ')}`);
    }
    if (dbLayer) {
      lines.push(`- **DB Tables (${dbLayer.items.length}):** ${dbLayer.items.join(', ')}`);
    }
    lines.push('');
  }

  // Code metrics
  if (ir.codeMap.totalFiles > 0) {
    lines.push('## Codebase');
    lines.push(`${ir.codeMap.totalFiles} source files, ~${ir.codeMap.totalLines.toLocaleString()} lines`);
    if (ir.codeMap.largestFiles.length > 0) {
      const top = ir.codeMap.largestFiles.slice(0, 5)
        .map(f => `${f.path.split('/').pop()} (${f.lines} lines)`)
        .join(', ');
      lines.push(`Largest: ${top}`);
    }
    lines.push('');
  }
}

function renderKeyModulesSection(ir: ContextIR, lines: string[]): void {
  if (ir.architecture.hubModules.length > 0) {
    lines.push('## Key Modules');
    lines.push('Most imported modules:');
    for (const hub of ir.architecture.hubModules.slice(0, 10)) {
      lines.push(`- \`${hub.path}\` (${hub.importedBy} imports)`);
    }
    lines.push('');
  }
}

function renderActiveWorkSection(ir: ContextIR, lines: string[]): void {
  const inProgress = ir.activeWork.tasks.filter(t => t.status === 'in_progress');
  const todo = ir.activeWork.tasks.filter(t => t.status === 'todo');

  if (inProgress.length > 0 || todo.length > 0) {
    lines.push('## Active Work');
    if (inProgress.length > 0) {
      lines.push('In progress:');
      for (const t of inProgress) {
        lines.push(`- ${t.title}`);
      }
    }
    if (todo.length > 0) {
      const display = todo.slice(0, 5);
      lines.push('To do:');
      for (const t of display) {
        lines.push(`- ${t.title}`);
      }
      if (todo.length > 5) {
        lines.push(`- ... and ${todo.length - 5} more`);
      }
    }
    lines.push('');
  }

  if (ir.activeWork.git) {
    const g = ir.activeWork.git;
    lines.push('## Git');
    lines.push(`Branch: ${g.branch} | ${g.totalCommits} commits | ${g.recentCommits} this week`);
    if (g.uncommittedChanges > 0) {
      lines.push(`${g.uncommittedChanges} uncommitted changes`);
    }
    lines.push('');
  }

  renderExternalIssuesSection(ir, lines);
}

function renderExternalIssuesSection(ir: ContextIR, lines: string[]): void {
  const issues = ir.activeWork.externalIssues;
  if (!issues || issues.length === 0) return;

  lines.push('## GitHub Issues');
  for (const issue of issues.slice(0, 15)) {
    const labels = issue.labels.length > 0 ? ` [${issue.labels.join(', ')}]` : '';
    lines.push(`- #${issue.number}: ${issue.title}${labels}`);
  }
  if (issues.length > 15) {
    lines.push(`- ... and ${issues.length - 15} more`);
  }
  lines.push('');
}

function renderFocusSection(ir: ContextIR, lines: string[]): void {
  if (!ir.focusAreas || ir.focusAreas.length === 0) return;

  lines.push('## Focus Areas');
  lines.push('*Task-linked context: files and modules relevant to active work*');
  lines.push('');

  for (const area of ir.focusAreas) {
    lines.push(`### ${area.taskTitle}`);

    if (area.primaryFiles.length > 0) {
      lines.push('**Primary files:**');
      for (const f of area.primaryFiles) {
        lines.push(`- \`${f}\``);
      }
    }

    if (area.relatedModules.length > 0) {
      lines.push('**Related modules:**');
      for (const m of area.relatedModules) {
        lines.push(`- \`${m}\``);
      }
    }

    if (area.relevantExports.length > 0) {
      lines.push('**Key exports:**');
      for (const exp of area.relevantExports) {
        lines.push(`- ${exp.kind}: ${exp.name}`);
      }
    }

    lines.push('');
  }
}

function renderSmartSection(ir: ContextIR, lines: string[]): void {
  if (!ir.smartRecommendation) return;

  const rec = ir.smartRecommendation;
  lines.push('## Recommended Focus (Smart Context)');
  lines.push(`*${rec.workContext}*`);
  lines.push('');

  if (rec.activeFiles.length > 0) {
    lines.push('**Active files** (by relevance):');
    for (const file of rec.activeFiles) {
      const score = rec.relevanceScores.get(file) ?? 0;
      lines.push(`- \`${file}\` (score: ${score})`);
    }
    lines.push('');
  }

  if (rec.relatedModules.length > 0) {
    lines.push('**Related modules:**');
    for (const mod of rec.relatedModules) {
      lines.push(`- \`${mod}\``);
    }
    lines.push('');
  }

  if (rec.suggestedExports.length > 0) {
    lines.push('**Key exports in scope:**');
    for (const exp of rec.suggestedExports.slice(0, 15)) {
      lines.push(`- ${exp.kind}: \`${exp.name}\` in \`${exp.file}\``);
    }
    lines.push('');
  }
}

function renderConstraintsSection(ir: ContextIR, lines: string[]): void {
  // Environment variables
  if (ir.constraints.envVars.length > 0) {
    lines.push('## Environment Variables');
    lines.push(ir.constraints.envVars.join(', '));
    lines.push('');
  }

  // Scripts
  const scriptNames = Object.keys(ir.constraints.scripts);
  if (scriptNames.length > 0) {
    lines.push('## Scripts');
    for (const name of scriptNames) {
      lines.push(`- \`${name}\`: \`${ir.constraints.scripts[name]}\``);
    }
    lines.push('');
  }

  // Deploy
  if (ir.constraints.deployTarget || ir.constraints.ci) {
    lines.push('## Deployment');
    if (ir.constraints.deployTarget) lines.push(`Platform: ${ir.constraints.deployTarget}`);
    if (ir.constraints.ci) lines.push(`CI: ${ir.constraints.ci}`);
    lines.push('');
  }
}
